export const URL = 'http://krapipl.imumk.ru:8082/api/mobilev1/update'
export const LOAD_PARAMS = 'LOAD_PARAMS'
export const LOAD_CONTENTS = 'LOAD_CONTENTS'
export const FILTER = 'FILTER'
export const SEARCH = 'SEARCH'
export const IS_BONUS = 'IS_BONUS'
